version: "3"
services:
  hub:
    image: selenium/hub:4.27
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chromium:4.27
    shm_size: 2gb
    depends_on:
      - hub
    deploy:
      replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.27
    shm_size: 2gb
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443